title: "Tong Bao (鲍通)"
description: "Postdoctoral researcher at INAF – Osservatorio Astronomico di Brera"
baseurl: ""
url: "https://baotong6.github.io"

sass:
  sass_dir: _sass
  
theme: minimal-mistakes-jekyll


author:
  name: "Tong Bao"
  email: "baotong@smail.nju.edu.cn"
  avatar: "/thumbnail.png"

social:
  github: "https://github.com/baotong6"
  google_scholar: "https://scholar.google.com/citations?user=8Fr_PVwAAAAJ&hl=zh-CN&oi=sra"
  orcid: "https://orcid.org/my-orcid?orcid=0000-0002-5082-5049"

nav:
  - title: "About"
    url: "/about/"
  - title: "Research"
    url: "/research/"
  - title: "Projects"
    url: "/projects/"
  - title: "Publications"
    url: "/publications/"
  - title: "CV"
    url: "/bao_cv.pdf"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author: "Tong Bao"
      comments: false

minimal_mistakes_skin: "personal"
header_pages:
  - index.md
